#!/bin/bash
#make jum directory in slate
mkdir jum

#create an environment for jum
conda create -n jum -c bioconda samtools=1.3.1 bedtools=2.26.0 star r-base bioconductor-dexseq
conda activate jum

#Install Perl with required modules -- Array::Utils and Statistics::Descriptive
wget -O- http://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib
module load perl
cpanm Array::Utils 
cpanm Statistics::Descriptive

#Open R studio 4.2.1 (has to be 4.2.X or up)
$ R
> if (!require("BiocManager", quietly = TRUE))
> install.packages("BiocManager")
> BiocManager::install(version = "3.16")
> BiocManager::install("DEXSeq")

#Download JUM package from here (https://github.com/qqwang-berkeley/JUM/releases)
#I downloaded JUM_3.0.0.tar.gz to desktop 
#copy to slate directory from Desktop
scp JUM_3.0.0.tar.gz /N/slate/emierdma/jum

#in jum directory, unzip JUM_3.0.0.tar.gz
tar -xf JUM_3.0.0.tar

# Copy and paste read files (.fastq) into jum directory

#Assign Variables
ASSEMBLY='ftp://ftp.wormbase.org/pub/wormbase/releases/WS275/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS275.genomic.fa.gz'
ANNOTATION='ftp://ftp.wormbase.org/pub/wormbase/releases/WS275/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS275.canonical_geneset.gtf.gz'

# Generate STAR Genome Index 
# Make a directory to store the genome files
mkdir -p genome/index


# Download and unpack the genome assembly.
curl $ASSEMBLY | gunzip > ./genome/assembly.fasta


# Download and unpack the genome annotation.
curl $ANNOTATION | gunzip > ./genome/annotation.gtf


# Create the STAR genome index
STAR --runThreadN 3 --runMode genomeGenerate --genomeDir genome/index --genomeFastaFiles genome/assembly.fasta --sjdbGTFfile genome/annotation.gtf --sjdbOverhang 99

# 1st pass mapping and copy selected STAR outputs from the 1st mapping to a folder named as 1st_SJ 
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix ctrl_1 --readFilesIn GSF3037-Hundley-EE_N2_germlines_5-1_S1_R1_001.fastq --outSJfilterReads Unique
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix ctrl_2 --readFilesIn GSF3037-Hundley-EE_N2_germlines_5-2_S2_R1_001.fastq --outSJfilterReads Unique
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix ctrl_3 --readFilesIn GSF3037-Hundley-EE_N2_germlines_5-3_S3_R1_001.fastq --outSJfilterReads Unique
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix treat_1 --readFilesIn GSF3037-Hundley-EE_adr2_germlines_5-2_S4_R1_001.fastq --outSJfilterReads Unique
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix treat_2 --readFilesIn GSF3037-Hundley-EE_adr2_germlines_5-3_S5_R1_001.fastq --outSJfilterReads Unique
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix treat_3 --readFilesIn GSF3037-Hundley-EE_adr2_germlines_5-4_S6_R1_001.fastq --outSJfilterReads Unique
mkdir 1st_SJ
rm *Aligned.out.sam
mv ctrl* 1st_SJ
mv treat* 1st_SJ

# 2nd pass mapping 
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix ctrl_1 --readFilesIn GSF3037-Hundley-EE_N2_germlines_5-1_S1_R1_001.fastq --outSJfilterReads Unique --outSAMstrandField intronMotif --outFilterMultimapNmax 1 -sjdbFileChrStartEnd 1st_SJ/ctrl_1SJ.out.tab 1st_SJ/ctrl_2SJ.out.tab 1st_SJ/ctrl_3SJ.out.tab 1st_SJ/treat_1SJ.out.tab 1st_SJ/treat_2SJ.out.tab 1st_SJ/treat_3SJ.out.tab
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix ctrl_2 --readFilesIn GSF3037-Hundley-EE_N2_germlines_5-2_S2_R1_001.fastq --outSJfilterReads Unique --outSAMstrandField intronMotif --outFilterMultimapNmax 1 -sjdbFileChrStartEnd 1st_SJ/ctrl_1SJ.out.tab 1st_SJ/ctrl_2SJ.out.tab 1st_SJ/ctrl_3SJ.out.tab 1st_SJ/treat_1SJ.out.tab 1st_SJ/treat_2SJ.out.tab 1st_SJ/treat_3SJ.out.tab
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix ctrl_3 --readFilesIn GSF3037-Hundley-EE_N2_germlines_5-3_S3_R1_001.fastq --outSJfilterReads Unique --outSAMstrandField intronMotif --outFilterMultimapNmax 1 -sjdbFileChrStartEnd 1st_SJ/ctrl_1SJ.out.tab 1st_SJ/ctrl_2SJ.out.tab 1st_SJ/ctrl_3SJ.out.tab 1st_SJ/treat_1SJ.out.tab 1st_SJ/treat_2SJ.out.tab 1st_SJ/treat_3SJ.out.tab
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix treat_1 --readFilesIn GSF3037-Hundley-EE_adr2_germlines_5-2_S4_R1_001.fastq --outSJfilterReads Unique --outSAMstrandField intronMotif --outFilterMultimapNmax 1 -sjdbFileChrStartEnd 1st_SJ/ctrl_1SJ.out.tab 1st_SJ/ctrl_2SJ.out.tab 1st_SJ/ctrl_3SJ.out.tab 1st_SJ/treat_1SJ.out.tab 1st_SJ/treat_2SJ.out.tab 1st_SJ/treat3SJ.out.tab
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix treat_2 --readFilesIn GSF3037-Hundley-EE_adr2_germlines_5-3_S5_R1_001.fastq --outSJfilterReads Unique --outSAMstrandField intronMotif --outFilterMultimapNmax 1 -sjdbFileChrStartEnd 1st_SJ/ctrl_1SJ.out.tab 1st_SJ/ctrl_2SJ.out.tab 1st_SJ/ctrl_3SJ.out.tab 1st_SJ/treat_1SJ.out.tab 1st_SJ/treat_2SJ.out.tab 1st_SJ/treat3SJ.out.tab
STAR --runThreadN 3 --genomeDir genome/index --outFileNamePrefix treat_3 --readFilesIn GSF3037-Hundley-EE_adr2_germlines_5-4_S6_R1_001.fastq --outSJfilterReads Unique --outSAMstrandField intronMotif --outFilterMultimapNmax 1 -sjdbFileChrStartEnd 1st_SJ/ctrl_1SJ.out.tab 1st_SJ/ctrl_2SJ.out.tab 1st_SJ/ctrl_3SJ.out.tab 1st_SJ/treat_1SJ.out.tab 1st_SJ/treat_2SJ.out.tab 1st_SJ/treat3SJ.out.tab

# Convert and sort the resulted alignment files (please use the exact naming nomenclature as shown below). Here we show ctrl 1 sample as an example but users need to do this for all the samples:
samtools view -bS ctrl1Aligned.out.sam > ctrl1Aligned.out.bam
samtools sort -o ctrl1Aligned.out_sorted.bam -T ctrl1_temp ctrl1Aligned.out.bam 
samtools index ctrl1Aligned.out_sorted.bam

samtools view -bS ctrl2Aligned.out.sam > ctrl2Aligned.out.bam
samtools sort -o ctrl2Aligned.out_sorted.bam -T ctrl2_temp ctrl2Aligned.out.bam 
samtools index ctrl2Aligned.out_sorted.bam

samtools view -bS ctrl3Aligned.out.sam > ctrl3Aligned.out.bam
samtools sort -o ctrl3Aligned.out_sorted.bam -T ctrl3_temp ctrl3Aligned.out.bam 
samtools index ctrl3Aligned.out_sorted.bam

samtools view -bS treat1Aligned.out.sam > treat1Aligned.out.bam
samtools sort -o treat1Aligned.out_sorted.bam -T treat1_temp treat1Aligned.out.bam 
samtools index treat1Aligned.out_sorted.bam

samtools view -bS treat2Aligned.out.sam > treat2Aligned.out.bam
samtools sort -o treat2Aligned.out_sorted.bam -T treat2_temp treat1Aligned.out.bam 
samtools index treat2Aligned.out_sorted.bam

samtools view -bS treat3Aligned.out.sam > treat3Aligned.out.bam
samtools sort -o treat3Aligned.out_sorted.bam -T treat3_temp treat1Aligned.out.bam 
samtools index treat3Aligned.out_sorted.bam

rm *Aligned.out.bam
