#!/bin/bash

#Make directory for variant calling within slate folder for project (/N/slate/emierdma/GSF3231)

mkdir Variantcall

#copy genome file, snp file and aligned bam into Variantcall directory

scp assembly.fasta 
scp c.elegans_WS275.snps.sorted.bed
scp *.merged.bam

#load samtools

module load samtools

#remove duplicate reads from bam file (takes ~5 minutes per file)

samtools rmdup GSF3231-EE-N2.merged.bam N2inputfile.nodup.bam
samtools rmdup GSF3231-EE-adr1.merged.bam adr1inputfile.nodup.bam

#Call the variant and clean up the output file with one line (took about 20 minutes for one file)

bcftools mpileup -I -t DP4 -f assembly.fasta N2inputfile.nodup.bam |awk'$5!="<*>"'| tail -n +30 > N2.rmdup.mpileup.vcf
bcftools mpileup -I -t DP4 -f assembly.fasta adr1inputfile.nodup.bam |awk'$5!="<*>"'| tail -n +30 > adr1.rmdup.mpileup.vcf

#activate environment containing python 3.8.6

conda activate Variant

#copy variant.py file into Variantcall directory (in terminal, off carbonate)

scp ~/Desktop/variant.py emierdma@carbonate.uits.iu.edu:/N/slate/emierdma/GSF3231/Variantcall

#convert vcf files to csv to open in excel

python variant.py --v N2.rmdup.mpileup.vcf --snp WS275.snps.sorted.bed --o N2variant.csv 
python variant.py --v adr1.rmdup.mpileup.vcf --snp WS275.snps.sorted.bed --o adr1variant.csv
